default:
  url:     'http://localhost:3000'
  default_image: 'http://localhost:3000'
  default_sub_category_image: ''

development:
  url:     'http://localhost:3000'
  default_image: 'http://localhost:3000/default_image.png'

production:
  url:     'https://api.covid-19.clicksandbox.com'
  default_image: 'https://api.covid-19.clicksandbox.com/default_image.png'
